Models/Articulo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Imagen = new HashSet<Imagen>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public int IdTopico { get; set; }
        public bool visible { get; set; }
    
        public virtual Topico Topico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagen> Imagen { get; set; }
    }
}

Controllers/ArticuloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediLab.Models;
using MediLab.Controllers.MyClasses;
using System.Web.Routing;
using System.Globalization;

namespace MediLab.Controllers
{
    public class ArticuloController : Controller
    {
        MedicinaEntities db;
        public ArticuloController()
        {
            db = new MedicinaEntities();

        }

        public ActionResult Index(ResultSet response = null,int topico = -1, int page = 1, int pageSize = 5)
        {
            ViewBag.topico = topico;
            ViewBag.Operacion = response;
            var articulos = GetArticulosPaginados(topico, page, pageSize);
            return View(articulos.AsEnumerable());
        }

        public List<Articulo> GetArticulosPaginados(int topico, int page = 1, int pageSize = 5)
        {
            System.Diagnostics.Debug.WriteLine(String.Format("Ingresando a obtiene articulos {0}", System.DateTime.Now));
            if (page <= 0)
            {
                page = 1;
            }
            if (pageSize <= 0)
            {
                pageSize = 5;
            }
          
            int totalRecord = db.Articulo.Where(s => (s.IdTopico.Equals(topico) && !topico.Equals(-1) && s.visible.Equals(true)) || (s.IdTopico.Equals(s.IdTopico) && topico.Equals(-1))).Count();
            ViewBag.dbcount = (totalRecord / pageSize) + ((totalRecord % pageSize) > 0 ? 1 : 0);
            var articulos = db.Articulo.Where(s => (s.IdTopico.Equals(topico) && !topico.Equals(-1) && s.visible.Equals(true)) || (s.IdTopico.Equals(s.IdTopico) && topico.Equals(-1))).OrderBy(s => s.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            return articulos;
        }
        public JsonResult BuscarArticulo(string term)
        {
            var resultado = db.Articulo.Where(s => s.Titulo.Contains(term))
                .Select(s => new { value = s.Titulo, Id = s.Id }).Take(5).ToList();
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetArticulo(int codigo)
        {

            var articulo = db.Articulo.Where(s => s.Id.Equals(codigo)).FirstOrDefault();
            if (articulo != null)
            {
                return View(articulo);
            }
            else
            {
                ResultSet response = new ResultSet();
                response.Code = -1;
                response.Msg = String.Format("El artículo seleccionado ya no existe");
                return RedirectToAction("Index", new RouteValueDictionary(response));

            }
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost,ValidateInput(false)]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                ResultSet response = new ResultSet();
                Articulo articulo = new Articulo()
                {
                    Titulo = collection["Titulo"].Trim(),
                    Comentarios = collection["Comentarios"].Trim(),
                    FechaPublicacion = DateTime.Now,
                    IdTopico = Convert.ToInt32(collection["IdTopico"]),
                    visible = Convert.ToBoolean(collection["visible"].Split(',')[0])
                };
                db.Articulo.Add(articulo);
                db.SaveChanges();
                response.Code = 1;
                response.Msg = String.Format("Se creó el artículo {0}", articulo.Titulo);               
                return RedirectToAction("Index", new RouteValueDictionary(response));
              

            }
            catch(Exception ex)
            {
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            Articulo articulo = db.Articulo.Where(s => s.Id.Equals(id)).FirstOrDefault();
            if (articulo != null)
            {
                return View(articulo);
            }
            else
            {
                ResultSet response = new ResultSet();
                response.Code = -1;
                response.Msg = String.Format("El artículo seleccionado ya no existe");
                return RedirectToAction("Index", new RouteValueDictionary(response));

            }
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {

                ResultSet response = new ResultSet();
                Articulo articulo = db.Articulo.Where(s => s.Id.Equals(id)).FirstOrDefault();
                if (articulo != null)
                {
                    articulo.Titulo = collection["Titulo"].Trim();
                    articulo.Comentarios = collection["Comentarios"].Trim();
                    articulo.IdTopico = Convert.ToInt32(collection["IdTopico"]);
                    articulo.visible = Convert.ToBoolean(collection["visible"].Split(',')[0]);
                    db.SaveChanges();
                    response.Code = 1;
                    response.Msg = String.Format("Se editó el articulo {0}", articulo.Titulo);
                }
                else
                {
                    response.Code = -1;
                    response.Msg = String.Format("El artículo seleccionado ya no existe");
                }             
                return RedirectToAction("Index", new RouteValueDictionary(response)); 
               

            }
            catch(Exception ex)
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                ResultSet response = new ResultSet();
                Articulo articulo = db.Articulo.Where(s => s.Id.Equals(id)).FirstOrDefault();
                if (articulo != null)
                {
                    db.Articulo.Remove(articulo);
                    db.SaveChanges();
                    response.Code = 1;
                    response.Msg = String.Format("Se borró el articulo {0}", articulo.Titulo);
                    
                }
                else
                {
                    response.Code = -1;
                    response.Msg = String.Format("El artículo seleccionado ya no existe");
                }
                return RedirectToAction("Index", new RouteValueDictionary(response));

            }
            catch
            {
                return View();
            }
        }     
    }
}

Views/Articulo/Create.cshtml
@model MediLab.Models.Articulo


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style>
        .borderClass {
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>


   <script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script>

    
    <!--<script src="http://tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script type="application/x-javascript">

        tinymce.init({selector:'#Comentarios'});

    </script>-->
   <script type="text/javascript">
//<![CDATA[
  bkLib.onDomLoaded(function() {
        new nicEditor().panelInstance('misComentarios');

  });
  //]]>
    </script>



  <!--<script src="http://tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script>

        tinymce.init({
            selector: '#misComentarios',  // change this value according to your HTML
            plugins: 'advlist autolink link image lists charmap print preview'
        });

    </script>-->


</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Crear Articulo</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div id="error">
            </div>
            <div class="form-group">               
                <label class="control-label col-md-2">Título</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", @maxlength = "50", @autocomplete = "off" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                    <span id="counterTitulo" style="color:#FF6601;"></span>
                </div>
            </div>

            <div class="form-group">              
                <label class="control-label col-md-2">Tópico</label>
                <div class="col-md-10">
                    @Html.EditorFor(model=>model.Topico.Nombre, new { htmlAttributes = new { @class = "form-control",@id="buscador", @maxlength = "30",@autocomplete = "off" } })
                    @Html.ValidationMessageFor(model => model.Topico.Nombre, "", new { @class = "text-danger" }) 
                    <span id="counterTopico" style="color:#FF6601;"></span>                   
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Publicado", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="form-check">
                        <label class="checkbox-inline">
                            @Html.CheckBoxFor(model => model.visible)
                        </label>
                    </div>
                </div>
            </div>         
    
            <div class="form-group">
                @Html.LabelFor(model => model.Comentarios, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">                   
                   @Html.TextAreaFor(model => model.Comentarios, 15, 50, htmlAttributes: new { @class = "form-control", style = "width: 100%; max-width: 100%;", @maxlength = "8000",@autocomplete = "off" ,@id="misComentarios"})
                   @Html.ValidationMessageFor(model => model.Comentarios, "", new { @class = "text-danger"})                 
                </div>
            </div>       
                        @Html.HiddenFor(model=>model.IdTopico)
            
                        
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar Cambios" onclick="return validatefields();" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
    
    <div>
        <a href='@Url.Action("Index", "Articulo")'>
            <img src="https://cdn.icon-icons.com/icons2/217/PNG/512/checklist_25365.png" data-toggle="tooltip" data-placement="top" title="Volver al listado" width="30" height="30" />
        </a>
    </div>
</body>
</html>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



<script>
    function validatefields() {

        $("#error").removeClass('alert alert-danger');
        $("#Titulo").removeClass('borderClass');
        $("#buscador").removeClass('borderClass');
        $("#Comentarios").removeClass('borderClass');
        $("#error").html("");
        var error_signal = 0
        var msg = "";
        var field = "";
        var valor = $.trim($("#Titulo").val());
        if (valor.length == 0) {
            error_signal = 1;
            msg = "Complete campo <b>Título</b>";
            field = "#Titulo";
        }
        else {
            valor = $.trim($("#buscador").val());
            if (valor.length == 0) {
                error_signal = 1;
                msg = "Complete campo <b>Tópico</b>";
                field = "#buscador";
            }

            else {
                valor = $("#IdTopico").val();
                if (valor == 0) {
                    error_signal = 1;
                    msg = "El tópico indicado no existe";
                    field = "#buscador";
                }               
            }
        }
        if (error_signal == 1) {
            $("#error").addClass("alert alert-danger");
            $("#error").html("<strong>Atención!</strong> " + msg);
            $(field).addClass('borderClass');
            return false;
        }
        return true;
    }

</script>



<script>
 $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
 });




 $('#Titulo').blur(function () {
     var valor = $('#Titulo').val()
     $('#Titulo').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
 });

 $('#buscador').blur(function () {
     var valor = $('#buscador').val()
     $('#buscador').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
 });

 $("#Titulo").keyup(function () {
     $("#counterTitulo").text("Caracteres restantes: " + (50 - $(this).val().length));
 });

 $("#buscador").keyup(function () {
     $("#counterTopico").text("Caracteres restantes: " + (30 - $(this).val().length));
 });


    $("#buscador").autocomplete(
       {
           minLength: 3, //Empieza a buscar a partir de los 3 caracteres ingresados
           focus: function (event, ui) {
               event.preventDefault(); //Con esta llamada evito que se cargue con el value del autocomplete
               $("#buscador").val(ui.item.label);

           },
           select: function (event, ui) { //Cuando finaliza configuro los valores del campo oculto
               event.preventDefault();
               $("#buscador").val(ui.item.label);
               $("#IdTopico").val(ui.item.value);
           },
           source: function (request, response) {

               $.ajax({
                   url: '/Topico/BuscarTopico',
                   type: 'POST',
                   data: { term: $("#buscador").val() },
                   cache: false,
                   dataType: 'json',
                   success: function (json) {
                       if (json.length > 0) {
                           response($.map(json, function (data) {
                               return {
                                   label: data.value,
                                   value: data.Id
                               };
                           }));
                       }
                       else { $("#IdTopico").val(0); } //Si no lo encuentra limpia el campo oculto del tópico

                   },
               })

           }
       }
    );
</script>

Views/Articulo/Edit.cshtml
@model MediLab.Models.Articulo


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <style>
        .borderClass {
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>

    <script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script>
    <!--<script src="http://tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script type="application/x-javascript">

        tinymce.init({selector:'#Comentarios'});

    </script>-->
    <script type="text/javascript">
//<![CDATA[
  bkLib.onDomLoaded(function() {
        new nicEditor().panelInstance('misComentarios');
  });
      </script>
</head>
<body>
    <div class="container">
        @using (Html.BeginForm())
        {

            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Editar Articulo</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                <div id="error">
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", @maxlength = "50", @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                        <span id="counterTitulo" style="color:#FF6601;"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Tópico</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Topico.Nombre, new { htmlAttributes = new { @class = "form-control", @id = "buscador", @maxlength = "30", @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.IdTopico, "", new { @class = "text-danger" })
                        <span id="counterTopico" style="color:#FF6601;"></span>
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Publicado", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="form-check">
                            <label class="checkbox-inline">
                                @Html.CheckBoxFor(model => model.visible)
                            </label>
                        </div>
                    </div>
                </div>   
                <div class="form-group">
                    @Html.LabelFor(model => model.Comentarios, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Comentarios, 15, 50, htmlAttributes: new { @class = "form-control", style = "width: 100%; max-width: 100%;", @maxlength = "8000",@id="misComentarios" })
                        @Html.ValidationMessageFor(model => model.Comentarios, "", new { @class = "text-danger" })
                        <span id="counter" style="color:#FF6601;"></span>
                    </div>
                </div>
                @Html.HiddenFor(model => model.IdTopico)

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar Cambios" onclick="return validatefields();" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
    </div>

    <div>
        <a href='@Url.Action("Index", "Articulo")'>
            <img src="https://cdn.icon-icons.com/icons2/217/PNG/512/checklist_25365.png" data-toggle="tooltip" data-placement="top" title="Volver al listado" width="30" height="30" />
        </a>
    </div>
</body>
</html>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    function validatefields() {

        $("#error").removeClass('alert alert-danger');
        $("#Titulo").removeClass('borderClass');
        $("#buscador").removeClass('borderClass');
        $("#Comentarios").removeClass('borderClass');
        $("#error").html("");
        var error_signal = 0
        var msg = "";
        var field = "";
        var valor = $.trim($("#Titulo").val());
        if (valor.length == 0) {
            error_signal = 1;
            msg = "Complete campo <b>Título</b>";
            field = "#Titulo";
        }
        else {
            valor = $.trim($("#buscador").val());
            if (valor.length == 0) {
                error_signal = 1;
                msg = "Complete campo <b>Tópico</b>";
                field = "#buscador";
            }
            else {
                valor = $("#IdTopico").val();
                if (valor == 0) {
                    error_signal = 1;
                    msg = "El tópico indicado no existe";
                    field = "#buscador";
                }
              
            }
        }

        if (error_signal == 1) {
            $("#error").addClass("alert alert-danger");
            $("#error").html("<strong>Atención!</strong> " + msg);
            $(field).addClass('borderClass');
            return false;
        }
        return true;
    }

</script>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });


    $('#Titulo').blur(function () {
        var valor = $('#Titulo').val()
        $('#Titulo').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
    });

    $('#buscador').blur(function () {
        var valor = $('#buscador').val()
        $('#buscador').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
    });


    $("#Titulo").keyup(function () {
        $("#counterTitulo").text("Caracteres restantes: " + (50 - $(this).val().length));
    });

    $("#buscador").keyup(function () {
        $("#counterTopico").text("Caracteres restantes: " + (30 - $(this).val().length));
    });
    
    $("#buscador").autocomplete(
       {
           minLength: 3, //Empieza a buscar a partir de los 3 caracteres ingresados
           focus: function (event, ui) {
               event.preventDefault(); //Con esta llamada evito que se cargue con el value del autocomplete
               $("#buscador").val(ui.item.label);

           },
           select: function (event, ui) { //Cuando finaliza configuro los valores del campo oculto
               event.preventDefault();
               $("#buscador").val(ui.item.label);
               $("#IdTopico").val(ui.item.value);
           },
           source: function (request, response) {

               $.ajax({
                   url: '/Topico/BuscarTopico',
                   type: 'POST',
                   data: { term: $("#buscador").val() },
                   cache: false,
                   dataType: 'json',
                   success: function (json) {
                       if (json.length > 0) {
                           response($.map(json, function (data) {
                               return {
                                   label: data.value,
                                   value: data.Id
                               };
                           }));
                       }
                       else { $("#IdTopico").val(0); } //Si no lo encuentra limpia el campo oculto del tópico

                   },
               })

           }
       }
    );
</script>

Views/Articulo/Index.cshtml
@model IEnumerable<MediLab.Models.Articulo>
@using MediLab.Controllers.MyClasses;

@{
    ViewBag.Title = "BuscarArticulos";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>

     .modal-dialog {
                position: initial;
            }
    .search_button {
        display: inline-block;
        border-radius: 4px;
        background-color: #008CBA;
        border: none;
        color: #FFFFFF;
        text-align: center;
        font-size: 16px;
        padding: 10px;
        width: 200px;
        transition: all 0.5s;
        cursor: pointer;
        margin: 5px;
    }

        .search_button span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
        }

            .search_button span:after {
                content: '\00bb';
                position: absolute;
                opacity: 0;
                top: 0;
                right: -20px;
                transition: 0.5s;
            }

        .search_button:hover span {
            padding-right: 25px;
        }

            .search_button:hover span:after {
                opacity: 1;
                right: 0;
            }

    .button {
        background-color: dodgerblue;
        border-radius: 12px;
        border: none;
        color: white;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 14px;
    }
</style>

@if (Model.Count() > 0 || Convert.ToInt32(ViewBag.topico) == -1)
{
    if (Convert.ToInt32(ViewBag.topico) != -1)
    {
        <h2>Lista de Artículos</h2>
    }   
    <p>
        @if (Convert.ToInt32(ViewBag.topico) == -1)
        {
            <a href='@Url.Action("Create", "Articulo")'>
                <img src="https://cdn.icon-icons.com/icons2/1146/PNG/512/1486485557-add-create-new-more-plus_81188.png" data-toggle="tooltip" data-placement="right" title="Crear nuevo Artículo" width="30" height="30" />
            </a>
        }
    </p>
    {
        if (ViewBag.Operacion != null)
        {
            ResultSet dato = (ResultSet)ViewBag.Operacion;
            if (dato.Code.Equals(1))
            {
                <div class="alert alert-success">
                    <strong>Operación Exitosa!</strong> @dato.Msg
                </div>
            }
            else
            {
                if (dato.Code.Equals(-1))
                {
                    <div class="alert alert-danger">
                        <strong>Operación Fallida!</strong> @dato.Msg
                    </div>
                }
            }
        }
    }

    <table class="table">
        <tr style="background-color:#D9EDF7">
            <th></th>
            <th>
                Título
            </th>
            <th>
                Fecha de Publicación
            </th>
            @if (Convert.ToInt32(ViewBag.topico) == -1)
            {
                <th>Tópico</th>
            }
            <th>¿Qué hacer?</th>
        </tr>

          @foreach (var item in Model)
          {

            <tr>
                <td>
                    @if (Convert.ToInt32(ViewBag.topico) != -1)
                    {
                        <img src="https://cdn2.iconfinder.com/data/icons/flat-seo-web-ikooni/128/flat_seo2-32-512.png" style="width:40px;height:40px;" />
                    }
                    else
                    {
                        <img src="https://cdn.icon-icons.com/icons2/112/PNG/512/documents_folder_18875.png" style="width:40px;height:40px;" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @DateTime.Parse(Html.DisplayFor(modelItem => item.FechaPublicacion).ToString()).ToLongDateString()
                </td>
                @if (Convert.ToInt32(ViewBag.topico) != -1)
                {
                    <td>
                        @Html.ActionLink("Ver mas..", "GetArticulo", new { codigo = item.Id }, new { @class = "btn btn-primary btn-large" })
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Topico.Nombre)
                    </td>
                    <td>
                        <a href='@Url.Action("Edit", "Articulo",new { id=item.Id })'>
                            <img src="https://cdn.icon-icons.com/icons2/215/PNG/256/edit-validated256_25237.png" data-toggle="tooltip" data-placement="top" title="Editar" width="20" height="20" />
                        </a>
                        &nbsp;
                        <a href='@Url.Action("Delete", "Articulo",new { id=item.Id })' title='@item.Titulo' onclick="return confirmDelete(this);">
                            <img src="https://cdn.icon-icons.com/icons2/624/PNG/512/Delete-80_icon-icons.com_57340.png" data-toggle="tooltip" data-placement="top" title="Borrar" width="20" height="20" />
                        </a>
                    </td>

                }
            </tr>
           }
    </table>
    for (int i = 1; i <= ViewBag.dbCount; i++)
    {
        <ul class="pagination">
            <li>@Html.ActionLink(@i.ToString(), "Index", "Articulo", new { topico = (int)ViewBag.topico, page = @i }, null)</li>
        </ul>
    }  
    
}
else
{
    <p></p>
    <p></p>
    <div class="alert alert-info">
        <strong>Información</strong> No existen articulos cargados para este tópico
    </div>
    <p></p>
    <table style="width: 100%; text-align: center;">
        <tr>
            <td>
                <img src="https://image.flaticon.com/icons/svg/123/123377.svg" width="150" height="150" />
            </td>
        </tr>
        <tr>
            <td>
                <button class="search_button" id="btnBuscador" onclick="location.href='@Url.Action("Index", "Home")'"><span>Volver a Buscar</span></button>
            </td>
        </tr>
    </table>
    <p></p>


}

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
<script>
    function confirmDelete(sender) {

        if ($(sender).attr("confirmed") == "true") { return true; }

        bootbox.confirm({
            title: "Atención",
            message: "<img src='https://cdn.icon-icons.com/icons2/20/PNG/256/process_thealert_2342.png' height='50' width='50'/>¿Confirma eliminar el item <b>" + sender.title + "</b>?",
            buttons: {
                confirm: {
                    label: 'Aceptar',
                    className: 'btn-success'
                },
                cancel: {
                    label: 'Cancelar',
                    className: 'btn-danger'
                }
            },
            callback: function (confirmed) {
                if (confirmed) {
                    $(sender).attr("confirmed", confirmed);
                    sender.click();
                }

            }
        });
        return false;
    }



        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
</script>