Models/Imagen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Comentarios { get; set; }
        public string Path { get; set; }
        public Nullable<int> esPadre { get; set; }
        public int IdArticulo { get; set; }
        public bool visible { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}

Controllers/ImagenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediLab.Models;
using MediLab.Controllers.MyClasses;
using System.Web.Routing;
using System.IO;

namespace MediLab.Controllers
{
    public class ImagenController : Controller
    {

        MedicinaEntities db;
        public ImagenController()
        {
            db = new MedicinaEntities();

        }
        public ActionResult Index(ResultSet response=null,int page=1,int pageSize=6)
        {
           
           if (page <= 0)
            {
                page = 1;
            }
            if (pageSize <= 0)
            {
                pageSize = 6;
            }
            ViewBag.Operacion = response;
            int totalRecord = db.Imagen.Count();
            ViewBag.dbcount= (totalRecord / pageSize) + ((totalRecord % pageSize) > 0 ? 1 : 0);
            var imagenes = db.Imagen.OrderBy(s => s.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            return View(imagenes.AsEnumerable());        
        }
     
      

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file,FormCollection collection)
        { try
            {
                if (file != null && file.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath("~/Imagenes"), Path.GetFileName(file.FileName));
                    if (!System.IO.File.Exists(path))
                    {
                        file.SaveAs(path); //Guardo el archivo en el server
                    }
                    ResultSet response = new ResultSet();
                    Imagen imagen = new Imagen()
                    {
                        Titulo = collection["Titulo"].Trim(),
                        Comentarios = collection["Comentarios"].Trim(),
                        Path = String.Format("~/Imagenes/{0}",file.FileName),
                        IdArticulo = Convert.ToInt32(collection["IdArticulo"])
                    };
                    db.Imagen.Add(imagen);
                    db.SaveChanges();
                    response.Code = 1;
                    response.Msg = String.Format("Se creó la imagen {0}", imagen.Titulo);
                    return RedirectToAction("Index", new RouteValueDictionary(response));
                }
                else return View();
            }
            catch(Exception ex)
            {
                return View();
            }            
        }
        public ActionResult Edit(int id)
        {
          

                Imagen imagen = db.Imagen.Where(s => s.Id.Equals(id)).FirstOrDefault();
                if (imagen != null)
                {
                    return View(imagen);
                }
                else
                {
                    ResultSet response = new ResultSet();
                    response.Code = -1;
                    response.Msg = String.Format("La imagen seleccionada ya no existe");
                    return RedirectToAction("Index", new RouteValueDictionary(response));
                }
            
           
        }
        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase file,int id, FormCollection collection)
        {
            try
            {
                ResultSet response = new ResultSet();
                Imagen imagen = db.Imagen.Where(s => s.Id.Equals(id)).FirstOrDefault();
                if (imagen != null)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        //Borramos el archivo anterior y damos de alta el nuevo archivo siempre y cuando el archivo no este en uso
                        String newpath = String.Format("~/Imagenes/{0}", file.FileName);
                        if (!this.imagenenuso(imagen.Path, id))
                        {
                            String oldfile = Server.MapPath(imagen.Path);
                            if (System.IO.File.Exists(oldfile))
                            {
                                System.IO.File.Delete(oldfile);
                            }
                        }
                        string absnewpath = Path.Combine(Server.MapPath("~/Imagenes"), Path.GetFileName(file.FileName));
                        if (!System.IO.File.Exists(absnewpath))
                        {
                            file.SaveAs(absnewpath);
                        }
                        imagen.Path = String.Format(newpath);
                    }
                    imagen.Titulo = collection["Titulo"].Trim();
                    imagen.Comentarios = collection["Comentarios"].Trim();
                    imagen.IdArticulo = Convert.ToInt32(collection["IdArticulo"]);
                    db.SaveChanges();
                    response.Code = 1;
                    response.Msg = String.Format("Se editó la imagen {0}", imagen.Titulo);
                }
                else
                {
                    response.Code = -1;
                    response.Msg = String.Format("La imagen seleccionada ya no existe");
                }  
                return RedirectToAction("Index", new RouteValueDictionary(response));
                
            }
            catch(Exception ex)
            {
                return View();
            }           
        }
        public ActionResult Details(int id)
        {
            MedicinaEntities db = new MedicinaEntities();
            Topico topico = db.Topico.Where(s => s.Id.Equals(id)).FirstOrDefault();
            if (topico != null)
            {
                return View(topico);
            }
            else
            {
                ResultSet response = new ResultSet();
                response.Code = -1;
                response.Msg = String.Format("La imagen seleccionada ya no existe");
                return RedirectToAction("Index", new RouteValueDictionary(response));
            }
        }
        private bool imagenenuso(String path, int id)
        {
            var img = db.Imagen.Where(s => (s.Path.Equals(path))
                                            && !(s.Id.Equals(id)))
                                     .FirstOrDefault();
            return (img!=null);            

        }
        
        public ActionResult Delete(int id)
        {
            ResultSet response = new ResultSet();
            try
            {
                
                Imagen imagen = db.Imagen.Where(s => s.Id.Equals(id)).FirstOrDefault();
                if (imagen != null)
                {
                    String path = Server.MapPath(imagen.Path);
                    if (System.IO.File.Exists(path) && !this.imagenenuso(imagen.Path, id))
                    {
                        System.IO.File.Delete(path);
                    }
                    db.Imagen.Remove(imagen);
                    db.SaveChanges();
                    response.Code = 1;
                    response.Msg = String.Format("Se borró la imagen {0}", imagen.Titulo);
                }
                else
                {
                    response.Code = -1;
                    response.Msg = String.Format("La imagen seleccionada ya no existe");
                }
                
            }
            catch(Exception exc)
            {
                return View();
            }
            return RedirectToAction("Index", new RouteValueDictionary(response));
        }      
    }
}

Views/Imagen/Create.cshtml
@model MediLab.Models.Imagen

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style>
        .btn-file {
            position: relative;
            overflow: hidden;
        }

            .btn-file input[type=file] {
                position: absolute;
                top: 0;
                right: 0;
                min-width: 100%;
                min-height: 100%;
                font-size: 100px;
                text-align: right;
                filter: alpha(opacity=0);
                opacity: 0;
                outline: none;
                background: white;
                cursor: inherit;
                display: block;
            }

        .borderClass {
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("Create","Imagen", FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Imagen</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div id="error">
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", @maxlength = "50",@autocomplete = "off" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                    <span id="counterTitulo" style="color:#FF6601;"></span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Articulo</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Articulo.Titulo, new { htmlAttributes = new { @class = "form-control", @id = "buscador", @maxlength = "50",@autocomplete = "off" } })
                    @Html.ValidationMessageFor(model => model.Articulo.Titulo, "", new { @class = "text-danger" })
                    <span id="counterArticulo" style="color:#FF6601;"></span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Comentarios, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Comentarios, 5, 5, htmlAttributes: new { @class = "form-control", style = "width: 40%; max-width: 40%;", @maxlength = "200" })
                    @Html.ValidationMessageFor(model => model.Comentarios, "", new { @class = "text-danger" })
                    <span id="counter" style="color:#FF6601;"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Imagen</label>
                <div class="col-md-10">
                    <span id="cargador" class="btn btn-primary btn-file">
                        Archivo... <input type="file" name="file" id="file" accept="image/*" />
                    </span>
                </div>
            </div>

            @Html.HiddenFor(model => model.IdArticulo)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar Cambios" onclick="return validatefields();" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        <a href='@Url.Action("Index", "Imagen")'>
            <img src="https://cdn.icon-icons.com/icons2/217/PNG/512/checklist_25365.png" data-toggle="tooltip" data-placement="top" title="Volver al listado" width="30" height="30" />
        </a>
    </div>
</body>
</html>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });

    $('#Titulo').blur(function () {
        var valor = $('#Titulo').val()
        $('#Titulo').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
    });

    $('#buscador').blur(function () {
        var valor = $('#buscador').val()
        $('#buscador').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
    });


    $("#Titulo").keyup(function () {
        $("#counterTitulo").text("Caracteres restantes: " + (50 - $(this).val().length));
    });

    $("#buscador").keyup(function () {
        $("#counterArticulo").text("Caracteres restantes: " + (50 - $(this).val().length));
    });

    $("#Comentarios").keyup(function () {      
        $("#counter").text("Caracteres restantes: " + (200 - $(this).val().length));
    });

    $("#buscador").autocomplete(
     {
         minLength: 3, //Empieza a buscar a partir de los 3 caracteres ingresados
         focus: function (event, ui) {
             event.preventDefault(); //Con esta llamada evito que se cargue con el value del autocomplete
             $("#buscador").val(ui.item.label);

         },
         select: function (event, ui) { //Cuando finaliza configuro los valores del campo oculto
             event.preventDefault();
             $("#buscador").val(ui.item.label);
             $("#IdArticulo").val(ui.item.value);
         },
         source: function (request, response) {

             $.ajax({
                 url: '/Articulo/BuscarArticulo',
                 type: 'POST',
                 data: { term: $("#buscador").val() },
                 cache: false,
                 dataType: 'json',
                 success: function (json) {
                     if (json.length > 0) {
                         response($.map(json, function (data) {
                             return {
                                 label: data.value,
                                 value: data.Id
                             };
                         }));
                     }
                     else { $("#IdArticulo").val(0); }//Si no lo encuentra limpia el campo oculto del articulo
                 },
             })

         }
     });
</script>
<script>
    function validatefields() {
        $("#error").removeClass('alert alert-danger');
        $("#Titulo").removeClass('borderClass');
        $("#buscador").removeClass('borderClass');
        $("#cargador").removeClass('borderClass');
        $("#Comentarios").removeClass('borderClass');
        $("#error").html("");
        var error_signal = 0
        var msg = "";
        var field = "";
        var valor = $.trim($("#Titulo").val());
        if (valor.length == 0) {
            error_signal = 1;
            msg = "Complete campo <b>Título</b>";
            field = "#Titulo";
        }
        else {
            valor = $.trim($("#buscador").val());
            if (valor.length == 0) {
                error_signal = 1;
                msg = "Complete campo <b>Artículo</b>";
                field = "#buscador";
            }
            else {
                valor = $("#IdArticulo").val();
                if (valor == 0) {
                    error_signal = 1;
                    msg = "El artículo indicado no existe";
                    field = "#buscador";
                }
                else {
                    valor = $.trim($("#Comentarios").val());
                    if (valor.length == 0) {
                        error_signal = 1;
                        msg = "Complete Comentarios";
                        field = "#Comentarios";
                    }
                    else {
                        valor = $("#file").val();
                        if (valor.length == 0) {
                            error_signal = 1;
                            msg = "Seleccione un archivo";
                            field = "#cargador";
                        }
                        else {//Extensiones de imagenes
                            extensions = new Array(".bmp",
                                                   ".gif",
                                                   ".jpg",
                                                   ".png",
                                                   ".psd",
                                                    ".ai",
                                                    ".cdr",
                                                    ".dwg",
                                                    ".svg",
                                                    ".raw",
                                                    ".nef"
                                               );
                            var fileExt = valor.substring(valor.lastIndexOf('.'));
                            if (extensions.indexOf(fileExt) < 0) {
                                error_signal = 1;
                                msg = "El archivo tiene que una imagen <b>(Extensiones válidas: .bmp,.gif,.jpg,.png,.psd,.ai,.cdr,.dwg,.svg,.raw,.nef)</b>";
                                field = "#cargador";
                            }
                        }


                    }
                }
            }
        }
        if (error_signal == 1) {
            $("#error").addClass("alert alert-danger");
            $("#error").html("<strong>Atención!</strong> " + msg);
            $(field).addClass('borderClass');
            return false;
        }
        return true;

    }

</script>

Views/Imagen/Edit.cshtml
@model MediLab.Models.Imagen


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>

    <style>
          .borderClass {
            border: 2px solid red;
            border-radius: 4px;
        }

        .btn-file {
            position: relative;
            overflow: hidden;
        }

            .btn-file input[type=file] {
                position: absolute;
                top: 0;
                right: 0;
                min-width: 100%;
                min-height: 100%;
                font-size: 100px;
                text-align: right;
                filter: alpha(opacity=0);
                opacity: 0;
                outline: none;
                background: white;
                cursor: inherit;
                display: block;
            }
    </style>
</head>
<body>
    @using (Html.BeginForm("Edit", "Imagen", FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken() 
           

            <div class="form-horizontal">
                <h4>Imagen</h4>
                <hr />
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                                <b>Vista Previa</b>
                            </a>
                        </h4>
                    </div>
                   <div id="collapse1" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <img src="@Url.Content(Model.Path)" />
                        </div>
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                <div id="error">
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", @maxlength = "50",@autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                        <span id="counterTitulo" style="color:#FF6601;"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Articulo</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Articulo.Titulo, new { htmlAttributes = new { @class = "form-control", @id = "buscador", @maxlength = "50", @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Articulo.Titulo, "", new { @class = "text-danger" })
                        <span id="counterArticulo" style="color:#FF6601;"></span>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Comentarios, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Comentarios, 5, 5, htmlAttributes: new { @class = "form-control", style = "width: 40%; max-width: 40%;", @maxlength = "200" })
                        @Html.ValidationMessageFor(model => model.Comentarios, "", new { @class = "text-danger" })
                        <span id="counter" style="color:#FF6601;"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Imagen</label>
                    <div class="col-md-10">
                        <span id="cargador" class="btn btn-primary btn-file">
                            Archivo... <input type="file" name="file" id="file" accept="image/*" />
                        </span>
                    </div>
                </div>   
                              

                @Html.HiddenFor(model => model.IdArticulo)
                @Html.HiddenFor(model => model.Path)
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar Cambios" onclick="return validatefields();"  class="btn btn-primary"  />
                    </div>
                </div>
            </div>
    }
    
    <div>
        <a href='@Url.Action("Index", "Imagen")'>
            <img src="https://cdn.icon-icons.com/icons2/217/PNG/512/checklist_25365.png" data-toggle="tooltip" data-placement="top" title="Volver al listado" width="30" height="30" />
        </a>
    </div>
</body>
</html>



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });

        $('#Titulo').blur(function () {
            var valor = $('#Titulo').val()
            $('#Titulo').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
        });

        $('#buscador').blur(function () {
            var valor = $('#buscador').val()
            $('#buscador').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
        });

        $("#Titulo").keyup(function () {
            $("#counterTitulo").text("Caracteres restantes: " + (50 - $(this).val().length));
        });

        $("#buscador").keyup(function () {
            $("#counterArticulo").text("Caracteres restantes: " + (50 - $(this).val().length));
        });


        $("#Comentarios").keyup(function () {
            $("#counter").text("Caracteres restantes: " + (200 - $(this).val().length));
        });

            $("#buscador").autocomplete(
            {
                minLength: 3, //Empieza a buscar a partir de los 3 caracteres ingresados
                focus: function (event, ui) {
                    event.preventDefault(); //Con esta llamada evito que se cargue con el value del autocomplete
                    $("#buscador").val(ui.item.label);

                },
                select: function (event, ui) { //Cuando finaliza configuro los valores del campo oculto
                    event.preventDefault();
                    $("#buscador").val(ui.item.label);
                    $("#IdArticulo").val(ui.item.value);
                },
                source: function (request, response) {

                    $.ajax({
                        url: '/Articulo/BuscarArticulo',
                        type: 'POST',
                        data: { term: $("#buscador").val() },
                        cache: false,
                        dataType: 'json',
                        success: function (json) {
                            if (json.length > 0) {
                                response($.map(json, function (data) {
                                    return {
                                        label: data.value,
                                        value: data.Id
                                    };
                                }));
                            }
                            else { $("#IdArticulo").val(0); } //Si no lo encuentra limpia el campo oculto del artículo
                        },
                    })

                }
            }
         );
        
</script>

<script>
    function validatefields() {
        $("#error").removeClass('alert alert-danger');
        $("#Titulo").removeClass('borderClass');
        $("#buscador").removeClass('borderClass');
        $("#cargador").removeClass('borderClass');
        $("#Comentarios").removeClass('borderClass');
        $("#error").html("");
        var error_signal = 0
        var msg = "";
        var field = "";
        var valor = $.trim($("#Titulo").val());
        if (valor.length == 0) {
            error_signal = 1;
            msg = "Complete campo <b>Título</b>";
            field = "#Titulo";
        }
        else {
            valor = $.trim($("#buscador").val());
            if (valor.length == 0) {
                error_signal = 1;
                msg = "Complete campo <b>Artículo</b>";
                field = "#buscador";
            }
            else {
                valor = $("#IdArticulo").val();
                if (valor == 0) {
                    error_signal = 1;
                    msg = "El artículo indicado no existe";
                    field = "#buscador";
                }
                else {
                    valor = $.trim($("#Comentarios").val());
                    if (valor.length == 0) {
                        error_signal = 1;
                        msg = "Complete Comentarios";
                        field = "#Comentarios";
                    }
                    else {
                        valor = $("#file").val().length == 0 ? $("#Path").val() : $("#file").val();
                        if (valor.length == 0) {
                            error_signal = 1;
                            msg = "Seleccione un archivo";
                            field = "#cargador";
                        }
                        else {//Extensiones de imagenes
                            extensions = new Array(".bmp",
                                                   ".gif",
                                                   ".jpg",
                                                   ".png",
                                                   ".psd",
                                                    ".ai",
                                                    ".cdr",
                                                    ".dwg",
                                                    ".svg",
                                                    ".raw",
                                                    ".nef"
                                               );
                            var fileExt = valor.substring(valor.lastIndexOf('.'));
                            if (extensions.indexOf(fileExt) < 0) {
                                error_signal = 1;
                                msg = "El archivo tiene que una imagen <b>(Extensiones válidas: .bmp,.gif,.jpg,.png,.psd,.ai,.cdr,.dwg,.svg,.raw,.nef)</b>";
                                field = "#cargador";
                            }
                        }

                    }
                }
            }
        }
        if (error_signal == 1) {
            $("#error").addClass("alert alert-danger");
            $("#error").html("<strong>Atención!</strong> " + msg);
            $(field).addClass('borderClass');
            return false;
        }
        return true;

    }

</script>