Models/Topico.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topico()
        {
            this.Articulo = new HashSet<Articulo>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Padre { get; set; }
        public Nullable<int> Hermano { get; set; }
        public bool visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
    }
}

Controllers/TopicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediLab.Models;
using MediLab.Controllers.MyClasses;
using System.Web.Routing;
using System.Collections;

namespace MediLab.Controllers
{
    public class TopicoController : Controller
    {

        MedicinaEntities db;
        public TopicoController()
        {
            db = new MedicinaEntities();

        }
        public ActionResult Index(ResultSet response=null,int page=1,int pageSize=5)
        {
            if (page <= 0)
            {
                page = 1;
            }
            if (pageSize <= 0)
            {
                pageSize = 5;
            }
            ViewBag.Operacion = response;           
            int totalRecord = db.Topico.Count();
            ViewBag.dbcount = (totalRecord / pageSize) + ((totalRecord % pageSize) > 0 ? 1 : 0);
            var topicos = db.Topico.OrderBy(s => s.Id).Skip((page - 1) * pageSize).Take(pageSize).ToList();        
            return View(topicos.AsEnumerable());
        }
     
        public JsonResult BuscarTopico(string term)
        {
           
            var resultado = db.Topico.Where(s => s.Nombre.Contains(term) && s.visible.Equals(true))
                .Select(s => new { value = s.Nombre, Id = s.Id }).Take(5).ToList();
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Create()
        {
            return View();
        }
        private bool topicoenuso(string topico,int id=0)
        {
            var item = db.Topico.Where(s => s.Nombre.Equals(topico) && (!s.Id.Equals(id))).FirstOrDefault();
            return (item != null);

        }


        [HttpPost]
        public ActionResult Create(FormCollection collection)
        { try
            {
                ResultSet response = new ResultSet();

                if (!topicoenuso(collection["Nombre"].Trim()))
                {
                    
                    Topico topico = new Topico()
                    {
                        Nombre = collection["Nombre"].Trim(),
                        Descripcion = collection["Descripcion"].Trim(),
                        visible=Convert.ToBoolean(collection["visible"].Split(',')[0])
                        

                    };

                    db.Topico.Add(topico);
                    db.SaveChanges();
                    response.Code = 1;
                    response.Msg = String.Format("Se creó el topico {0}", topico.Nombre);
                }        
                else
                {
                    response.Code = -1;
                    response.Msg = String.Format("El tópico {0} ya existe", collection["Nombre"].Trim());

                }
                return RedirectToAction("Index", new RouteValueDictionary(response));

            }
            catch(Exception exc)
            {
                return View();
            }            
        }
        public ActionResult Edit(int id)
        {
            Topico topico = db.Topico.Where(s => s.Id.Equals(id)).FirstOrDefault();
            if (topico != null)
            {
                return View(topico);
            }
            else
            {
                ResultSet response = new ResultSet();
                response.Code = -1;
                response.Msg = String.Format("El tópico seleccionado ya no existe");
                return RedirectToAction("Index", new RouteValueDictionary(response));
            }
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                ResultSet response = new ResultSet();
                Topico topico = db.Topico.Where(s => s.Id.Equals(id)).FirstOrDefault();
                if (topico != null)
                {
                    topico.Nombre = collection["Nombre"].Trim();
                    topico.Descripcion = collection["Descripcion"].Trim();
                    topico.visible = Convert.ToBoolean(collection["visible"].Split(',')[0]);
                    db.SaveChanges();
                    response.Code = 1;
                    response.Msg = String.Format("Se editó el topico {0}", topico.Nombre);
                    return RedirectToAction("Index", new RouteValueDictionary(response));
                }
                else
                {                   
                    response.Code = -1;
                    response.Msg = String.Format("El tópico seleccionado ya no existe");
                    return RedirectToAction("Index", new RouteValueDictionary(response));

                }
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            Topico topico = db.Topico.Where(s => s.Id.Equals(id)).FirstOrDefault();
            if (topico != null)
            {
                ViewBag.estado = (topico.visible) ? "Este tópico no se encuentra disponible para su visualización":"Este tópico se encuentra visible";
                return View(topico);
            }
            else
            {
                ResultSet response = new ResultSet();
                response.Code = -1;
                response.Msg = String.Format("El tópico seleccionado ya no existe");
                return RedirectToAction("Index", new RouteValueDictionary(response));

            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                ResultSet response = new ResultSet();
                Topico topico = db.Topico.Where(s => s.Id.Equals(id)).FirstOrDefault();
                if (topico != null)
                {
                    db.Topico.Remove(topico);
                    db.SaveChanges();
                    response.Code = 1;
                    response.Msg = String.Format("Se borró el topico {0}", topico.Nombre);
                    return RedirectToAction("Index", new RouteValueDictionary(response));
                }
                else
                {
                    response.Code = -1;
                    response.Msg = String.Format("El tópico seleccionado ya no existe");
                    return RedirectToAction("Index", new RouteValueDictionary(response));
                }
            }
            catch
            {
                return View();
            }
        }     
    }
}

Views/Topico/Create.cshtml
@model MediLab.Models.Topico


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style>  

        .borderClass {
            border: 2px solid red;
            border-radius: 4px;
        }
  
       
    </style>


</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Crear Topico</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div id="error">
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-wrench"></i></span>
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @maxlength = "30", @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })                       
                    </div>
                    <span id="counterTitulo" style="color:#FF6601;"></span>
                </div>

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-wrench"></i></span>
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @maxlength = "100", @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })                      
                    </div>                 
                    
                    <span id="counterDescripcion" style="color:#FF6601;"></span>
                 </div>
            </div>
            <div class="form-group">
               @Html.Label("Visible", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="form-check">
                        <label class="checkbox-inline">                            
                            @Html.CheckBoxFor(model=>model.visible)
                        </label>
                    </div>
                </div>
                </div>          
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar Cambios" onclick="return validatefields();" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        <a href='@Url.Action("Index", "Topico")'>
            <img src="https://cdn.icon-icons.com/icons2/217/PNG/512/checklist_25365.png" data-toggle="tooltip" data-placement="top" title="Volver al listado" width="30" height="30" />
        </a>
    </div>
</body>
</html>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>   
    function validatefields() {
        $("#error").removeClass('alert alert-danger');
        $("#Nombre").removeClass('borderClass');
        $("#Descripcion").removeClass('borderClass');
        $("#error").html("");
        var error_signal = 0
        var msg = "";
        var field = "";
        var valor = $.trim($("#Nombre").val());
        if (valor.length == 0) {
            error_signal = 1;
            msg = "Complete campo <b>Nombre</b>";
            field = "#Nombre";
        }
        else {
                 valor = $.trim($("#Descripcion").val());
                 if (valor.length == 0) {
                     error_signal = 1;
                     msg = "Complete campo <b>Descripción</b>";
                     field = "#Descripcion";
                 }

        }
        if (error_signal == 1) {
            $("#error").addClass("alert alert-danger");
            $("#error").html("<strong>Atención!</strong> " + msg);
            $(field).addClass('borderClass');
            return false;
        }
        return true;
    }
</script>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });

    $('#Nombre').blur(function () {        
        var valor = $('#Nombre').val()
        $('#Nombre').val(valor.charAt(0).toUpperCase()+valor.substr(1).toLowerCase());
    });

    $('#Descripcion').blur(function () {
        var valor = $('#Descripcion').val()
        $('#Descripcion').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
    });

    $("#Nombre").keyup(function () {
        $("#counterTitulo").text("Caracteres restantes: " + (30 - $(this).val().length));
    });

    $("#Descripcion").keyup(function () {
        $("#counterDescripcion").text("Caracteres restantes: " + (100 - $(this).val().length));
    });

</script>

Views/Topico/Details.cshtml
@model MediLab.Models.Topico

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Topico</h4>
        <hr />
        <div class="alert alert-info">
            <strong>@ViewBag.estado</strong> 
        </div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Descripcion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Descripcion)
            </dd> 
             
        </dl>
    </div>
    <p>
    

       
        <a href='@Url.Action("Index", "Topico")'>
            <img src="https://cdn.icon-icons.com/icons2/217/PNG/512/checklist_25365.png" data-toggle="tooltip" data-placement="top" title="Volver al listado" width="30" height="30" />
        </a>
        &nbsp;
        <a href='@Url.Action("Edit", "Topico",new { id=Model.Id })'>
            <img src="https://cdn.icon-icons.com/icons2/215/PNG/256/edit-validated256_25237.png" data-toggle="tooltip" data-placement="top" title="Editar" width="30" height="30" />
        </a>  

    </p>
</body>
</html>
@section scripts {


    <script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
    </script>
}

Views/Topico/Edit.cshtml
@model MediLab.Models.Topico



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <style>     

        .borderClass {
            border: 2px solid red;
            border-radius: 4px;
        }
    </style>

</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Editar Topico</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div id="error">
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-wrench"></i></span>
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @maxlength = "30", @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                     </div>
                     <span id="counterTitulo" style="color:#FF6601;"></span>
                    </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="input-group">                      
                            <span class="input-group-addon"><i class="glyphicon glyphicon-wrench"></i></span>
                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @maxlength = "100", @autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>                     
                     <span id="counterDescripcion" style="color:#FF6601;"></span>
                    </div>            
            </div>   
            <div class="form-group">
                @Html.Label("Visible", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="form-check">
                        <label class="checkbox-inline">
                            @Html.CheckBoxFor(model => model.visible)
                        </label>
                    </div>
                </div>
            </div>          
            
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                  <input type="submit" value="Guardar Cambios" onclick="return validatefields();" class="btn btn-primary" />                  
                    
                </div>
            </div>
        </div>
    }
    
    <div>     
        <a href='@Url.Action("Index", "Topico")'>
            <img src="https://cdn.icon-icons.com/icons2/217/PNG/512/checklist_25365.png" data-toggle="tooltip" data-placement="top" title="Volver al listado" width="30" height="30" />
        </a>
    </div>
</body>
</html>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });

        $('#Nombre').blur(function () {
            var valor = $('#Nombre').val()
            $('#Nombre').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
        });

        $('#Descripcion').blur(function () {
            var valor = $('#Descripcion').val()
            $('#Descripcion').val(valor.charAt(0).toUpperCase() + valor.substr(1).toLowerCase());
        });

        $("#Nombre").keyup(function () {
            $("#counterTitulo").text("Caracteres restantes: " + (30 - $(this).val().length));
        });

        $("#Descripcion").keyup(function () {
            $("#counterDescripcion").text("Caracteres restantes: " + (100 - $(this).val().length));
        });

</script>
<script>
    function validatefields() {
        $("#error").removeClass('alert alert-danger');
        $("#Nombre").removeClass('borderClass');
        $("#Descripcion").removeClass('borderClass');
        $("#error").html("");
        var error_signal = 0
        var msg = "";
        var field = "";
        var valor = $.trim($("#Nombre").val());
        if (valor.length == 0) {
            error_signal = 1;
            msg = "Complete campo <b>Nombre</b>";
            field = "#Nombre";
        }
        else {
                 valor = $.trim($("#Descripcion").val());
                 if (valor.length == 0) {
                     error_signal = 1;
                     msg = "Complete campo <b>Descripción</b>";
                     field = "#Descripcion";
                 }

        }
        if (error_signal == 1) {
            $("#error").addClass("alert alert-danger");
            $("#error").html("<strong>Atención!</strong> " + msg);
            $(field).addClass('borderClass');
            return false;
        }
        return true;
    }
</script>

Views/Topico/Index.cshtml
@model IEnumerable<MediLab.Models.Topico>
@using MediLab.Controllers.MyClasses;

<!DOCTYPE html>

<html>
<head>  
        <title>Galería de tópicos</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <style>
            .modal-dialog {
                position: initial;
            }
        </style>
  
</head>
<body>
    <p>
        <a href='@Url.Action("Create", "Topico")'>
            <img src="https://cdn.icon-icons.com/icons2/1146/PNG/512/1486485557-add-create-new-more-plus_81188.png" data-toggle="tooltip" data-placement="right" title="Crear nuevo tópico" width="30" height="30" /> 
        </a>
       
    </p>
    @{
        if (ViewBag.Operacion != null)
        {
            ResultSet dato = (ResultSet)ViewBag.Operacion;
            if (dato.Code.Equals(1))
            {
             <div class="alert alert-success">
            <strong>Operación Exitosa!</strong> @dato.Msg
            </div>
            }
            else
            {
                if (dato.Code.Equals(-1))
                {
                    <div class="alert alert-danger">
                        <strong>Operación Fallida!</strong> @dato.Msg
                    </div>
                }
            }
        }



    }
    
    <table class="table">
        <tr style="background-color:#D9EDF7">
            <th>

            </th>
            <th>
                Nombre
            </th>
            <th >
               Descripción
            </th>         
            <th>
                 ¿Qué hacer?
            </th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
               <img src="https://cdn.icon-icons.com/icons2/564/PNG/512/Idea_icon-icons.com_54173.png" width="30" height="30" />              
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>          
            <td>
                <a href='@Url.Action("Edit", "Topico",new { id=item.Id })'>
                    <img src="https://cdn.icon-icons.com/icons2/215/PNG/256/edit-validated256_25237.png" data-toggle="tooltip" data-placement="top" title="Editar" width="20" height="20" />
                </a>             
                &nbsp
                <a href='@Url.Action("Details", "Topico",new { id=item.Id })'>
                    <img src="https://cdn.icon-icons.com/icons2/39/PNG/128/xmag_search_find_export_locate_5984.png" data-toggle="tooltip" data-placement="top" title="Ver" width="20" height="20" />
                </a>
                &nbsp
                <a href='@Url.Action("Delete", "Topico",new { id=item.Id })' title='@item.Nombre' onclick="return confirmDelete(this);">
                    <img src="https://cdn.icon-icons.com/icons2/624/PNG/512/Delete-80_icon-icons.com_57340.png" data-toggle="tooltip" data-placement="top" title="Borrar" width="20" height="20" />
                </a>               
             
            </td>
        </tr>
    }
    
    </table>
    @for (int i = 1; i <= ViewBag.dbCount; i++)
    {
    <ul class="pagination">
        <li>@Html.ActionLink(@i.ToString(), "Index", "Topico", new { page = @i }, null)</li>
    </ul>
    }    
</body>
</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
<script>
    function confirmDelete(sender) {

        if ($(sender).attr("confirmed") == "true") { return true; }

        bootbox.confirm({
            title: "Atención",
            message: "<img src='https://cdn.icon-icons.com/icons2/20/PNG/256/process_thealert_2342.png' height='50' width='50'/> ¿Confirma eliminar el item <b>" + sender.title + "</b>?",
            buttons: {
                confirm: {
                    label: 'Aceptar',
                    className: 'btn-success'
                },
                cancel: {
                    label: 'Cancelar',
                    className: 'btn-danger'
                }
            },
            callback: function (confirmed) {
                if (confirmed) {
                    $(sender).attr("confirmed", confirmed);
                    sender.click();
                }

            }
        });
        return false;
    }


    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();

    });

</script>